### ISSUE TITLE
Won't load on Bootstrap 3

### ISSUE THREAD

**Issue by tofanelli** [thecodeassassin/bootstrap-remote-data#7]
hey man... hows going?

Look... i've been trying to make your plugin works, but I still couldn't. Even your demo in zip file isn't working....

Mind to give a little help please??

cheers =)

**Comment by thecodeassassin** [comment]
hey Tofanelli,

what seems to be the problem exactly? What version of bootstrap and jquery are you using?

**Comment by tofanelli** [comment]
Hey man....

actually i downloaded your demo and isn't working at all. I downloaded it, opened the "index.html" inside demo folder, and nope... not working.... may I ask you to try yourself downloading from here please?

Cheers =)

**Comment by thecodeassassin** [comment]
hey tofanelli, can you run a git pull? I fixed the issue you were having. It was caused by not defining the settings.

**Comment by tofanelli** [comment]
Hey thecode.... so, no deal yet... I just downloaded your new version, unzipped and only the tab with delay is kinda working.. starts to load, but in the end fails to load... am I doing something wrong? And the "normal" one too.... 

any thoughts?


Cheers =)
